version: "3"
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:8080"
    volumes:
      - /app/node_modules
      - .:/app
    restart: always
