# Dockerfilw with multi-step build process
# Base images - node:alpine and nginx

FROM node:alpine as builder
WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx as runner

COPY --from=builder /app/dist /usr/share/nginx/html