version: "3.4"
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:8080"
        volumes:
            - /app/node_modules
            - .:/app
    frontend_tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules # DO NOT TOUCH THIS DIRECTORY IN CONTAINER
            - .:/app
        command: ["npm", "run", "test"]