version: 2
jobs:
  build:
    docker:
      - image: node:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'npm install -g npm@latest'
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-s
      - run: 'npm install --save'
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 'npm run test'